# Generated by Django 4.2.4 on 2023-12-09 12:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0005_location_by_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location_by_user',
            new_name='LocationByUser',
        ),
    ]
